#!/bin/bash

echo "=========================================="
echo "SCDL-THREADED Test Script"
echo "=========================================="
echo ""
echo "✅ Installation successful!"
echo ""
echo "📍 Command location: $(which scdl-threaded)"
echo "📍 Version: $(scdl-threaded --version)"
echo ""
echo "🔧 Important Note about current implementation:"
echo "   The threaded_download_track function in scdl.py (line 445)"
echo "   is currently hardcoded to use 5 threads regardless of the --threads parameter."
echo ""
echo "   To make the --threads parameter work properly, you would need to change:"
echo "   Line 445: num_threads = 5"
echo "   To:       num_threads = kwargs.get('threads', 1) if isinstance(kwargs.get('threads'), int) else 1"
echo ""
echo "🎯 Usage Examples:"
echo ""
echo "  # Download a single track with 5 threads (currently hardcoded)"
echo "  scdl-threaded -l <track_url> --threads 5"
echo ""
echo "  # Download a playlist with concurrent downloads"
echo "  scdl-threaded -l <playlist_url> --threads 10"
echo ""
echo "  # Download user's favorites with threading"
echo "  scdl-threaded -l <user_url> -f --threads 8"
echo ""
echo "  # Download with custom path and threading"
echo "  scdl-threaded -l <url> --path ~/Music/SoundCloud --threads 5"
echo ""
echo "==========================================